updates:
  - name: "Bazel deps"
    targets:
      - "//..."
    patches:
      # This will catch ALL Bazel rules including rules_java, rules_jvm_external, etc.
      - groupId: "bazel_rules"
        groupName: "All Bazel rules"
        patterns:
          - "^rules_.*"   # Matches any rule starting with "rules_"
          - "^bazel_.*"   # Matches any rule starting with "bazel_"

      # Maven dependencies (both existing and future ones)
      - groupId: "maven_deps"
        groupName: "Maven dependencies"
        patterns:
          - "^com\\..*"      # Matches com.fasterxml, com.google, etc.
          - "^org\\..*"      # Matches org.springframework, org.mongodb, org.junit, etc.
          - "^io\\..*"       # For io.* dependencies