updates:
  - name: "Bazel deps"
    targets:
      - "//..."
    patches:
      # Your existing patterns are good
      - groupId: "bazel_rules"
        groupName: "All Bazel rules"
        patterns:
          - "^rules_.*"
          - "^bazel_.*"

      - groupId: "maven_deps"
        groupName: "Maven dependencies"
        patterns:
          - "^com\\..*"
          - "^org\\..*"
          - "^io\\..*"

# Add these settings
settings:
  pullRequests:
    enabled: true
    limit: 10  # Maximum number of open PRs
    branch:
      prefix: "steward"  # PRs will be created with this prefix
  commits:
    message: "chore: update ${groupName} to ${version}"
  labels:
    - "dependencies"