name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@95c9bf48d0c570bb3e28e57108f3450cd67c1a44 # v2

      - name: Mount bazel cache
        uses: actions/cache@f4b3439a656ba812b8cb417d2d49f9c810103092 # v3
        with:
          path: "~/.cache/bazel"
          key: bazel-${{ runner.os }}-${{ hashFiles('MODULE.bazel', '.bazelversion') }}
          restore-keys: bazel-${{ runner.os }}-

      - name: Build Java application
        run: bazel build //src/main/java/com/example/depwatch:depwatch

      - name: Build container
        run: bazel build //docker:tarball