name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel-${{ runner.os }}-${{ hashFiles('MODULE.bazel', '.bazelversion') }}
          restore-keys: bazel-${{ runner.os }}-

      - name: Build Java application
        run: bazel build //src/main/java/com/example/depwatch:depwatch

      - name: Build container
        run: bazel build //docker:tarball

  steward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run Bazel Steward
        uses: VirtusLab/bazel-steward@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: bazel-steward.yaml